import type { Metadata } from "next";
import { Archivo, Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import MouseCursorComponent from "@/components/MouseCursorComponent";
import Header from "@/components/Header";

const archivo = Archivo({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-archivo",
});

const inter = Inter({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${inter.variable} antialiased font-inter overflow-x-hidden`}
      >
        <MouseCursorComponent>
          <>
            <Header />
            {children}
            <Footer />
          </>
        </MouseCursorComponent>
         
      </body>
    </html>
  );
}
